### ISSUE TITLE
Current libdsm build error. Can anybody help

### ISSUE THREAD

**Issue by jiapei100** [videolabs/libdsm#111] opened 2017-06-14 20:09 UTC
Hi, I'm using Ubuntu 16.04.2, with GCC/G++ version (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

I failed to buld libdsm, with the following ERROR messages:

> @:.../libdsm$ make -j8
> make  all-am
> make[1]: Entering directory '/media/jiapei/Data/Downloads/videoprocessing/codecs/libdsm'
>   CCLD     dsm_discover
>   CCLD     dsm
>   CCLD     dsm_lookup
>   CCLD     dsm_inverse
> ./.libs/libdsm.so:. undefined/ .referencelibs /tolibdsm.so :` closesocketundefined' 
> reference to `closesocket'
> collect2: error: ld returned 1 exit status
> collect2: error: ld returned 1 exit status
> Makefile:756: recipe for target 'dsm_lookup' failed
> make[1]: *** [dsm_lookup] Error 1
> make[1]: *** Waiting for unfinished jobs....
> Makefile:750: recipe for target 'dsm_inverse' failed
> make[1]: *** [dsm_inverse] Error 1
> ./.libs/libdsm.so: undefined reference to `closesocket'
> collect2: error: ld returned 1 exit status
> ./.libs/libdsm.so: undefined reference to `closesocket'
> collect2: error: ld returned 1 exit status
> Makefile:738: recipe for target 'dsm' failed
> make[1]: *** [dsm] Error 1
> Makefile:744: recipe for target 'dsm_discover' failed
> make[1]: *** [dsm_discover] Error 1
> make[1]: Leaving directory '/media/jiapei/Data/Downloads/videoprocessing/codecs/libdsm'
> Makefile:508: recipe for target 'all' failed
> make: *** [all] Error 2
>

Can anybody give me a hand?

Cheers

**Comment by chouquette** [comment] 2017-08-28 10:08
Duplicate of #99

**Closed by chouquette** 2017-08-28 10:08 UTC
